# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/mygit/ds

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/mygit/ds

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/mygit/ds/CMakeFiles /root/mygit/ds/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/mygit/ds/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tree

# Build rule for target.
tree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tree
.PHONY : tree

# fast build rule for target.
tree/fast:
	$(MAKE) -f CMakeFiles/tree.dir/build.make CMakeFiles/tree.dir/build
.PHONY : tree/fast

#=============================================================================
# Target rules for targets named sort

# Build rule for target.
sort: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sort
.PHONY : sort

# fast build rule for target.
sort/fast:
	$(MAKE) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/build
.PHONY : sort/fast

#=============================================================================
# Target rules for targets named big_number

# Build rule for target.
big_number: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 big_number
.PHONY : big_number

# fast build rule for target.
big_number/fast:
	$(MAKE) -f CMakeFiles/big_number.dir/build.make CMakeFiles/big_number.dir/build
.PHONY : big_number/fast

#=============================================================================
# Target rules for targets named binary_search

# Build rule for target.
binary_search: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 binary_search
.PHONY : binary_search

# fast build rule for target.
binary_search/fast:
	$(MAKE) -f CMakeFiles/binary_search.dir/build.make CMakeFiles/binary_search.dir/build
.PHONY : binary_search/fast

#=============================================================================
# Target rules for targets named lc_reverse_int

# Build rule for target.
lc_reverse_int: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lc_reverse_int
.PHONY : lc_reverse_int

# fast build rule for target.
lc_reverse_int/fast:
	$(MAKE) -f CMakeFiles/lc_reverse_int.dir/build.make CMakeFiles/lc_reverse_int.dir/build
.PHONY : lc_reverse_int/fast

#=============================================================================
# Target rules for targets named subarray

# Build rule for target.
subarray: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 subarray
.PHONY : subarray

# fast build rule for target.
subarray/fast:
	$(MAKE) -f CMakeFiles/subarray.dir/build.make CMakeFiles/subarray.dir/build
.PHONY : subarray/fast

#=============================================================================
# Target rules for targets named lc_longest_palindrome

# Build rule for target.
lc_longest_palindrome: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lc_longest_palindrome
.PHONY : lc_longest_palindrome

# fast build rule for target.
lc_longest_palindrome/fast:
	$(MAKE) -f CMakeFiles/lc_longest_palindrome.dir/build.make CMakeFiles/lc_longest_palindrome.dir/build
.PHONY : lc_longest_palindrome/fast

#=============================================================================
# Target rules for targets named lc_longest_substring

# Build rule for target.
lc_longest_substring: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lc_longest_substring
.PHONY : lc_longest_substring

# fast build rule for target.
lc_longest_substring/fast:
	$(MAKE) -f CMakeFiles/lc_longest_substring.dir/build.make CMakeFiles/lc_longest_substring.dir/build
.PHONY : lc_longest_substring/fast

#=============================================================================
# Target rules for targets named lc_median_of_two_sorted_array

# Build rule for target.
lc_median_of_two_sorted_array: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lc_median_of_two_sorted_array
.PHONY : lc_median_of_two_sorted_array

# fast build rule for target.
lc_median_of_two_sorted_array/fast:
	$(MAKE) -f CMakeFiles/lc_median_of_two_sorted_array.dir/build.make CMakeFiles/lc_median_of_two_sorted_array.dir/build
.PHONY : lc_median_of_two_sorted_array/fast

#=============================================================================
# Target rules for targets named lc_two_sum

# Build rule for target.
lc_two_sum: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lc_two_sum
.PHONY : lc_two_sum

# fast build rule for target.
lc_two_sum/fast:
	$(MAKE) -f CMakeFiles/lc_two_sum.dir/build.make CMakeFiles/lc_two_sum.dir/build
.PHONY : lc_two_sum/fast

big_number.o: big_number.cc.o

.PHONY : big_number.o

# target to build an object file
big_number.cc.o:
	$(MAKE) -f CMakeFiles/big_number.dir/build.make CMakeFiles/big_number.dir/big_number.cc.o
.PHONY : big_number.cc.o

big_number.i: big_number.cc.i

.PHONY : big_number.i

# target to preprocess a source file
big_number.cc.i:
	$(MAKE) -f CMakeFiles/big_number.dir/build.make CMakeFiles/big_number.dir/big_number.cc.i
.PHONY : big_number.cc.i

big_number.s: big_number.cc.s

.PHONY : big_number.s

# target to generate assembly for a file
big_number.cc.s:
	$(MAKE) -f CMakeFiles/big_number.dir/build.make CMakeFiles/big_number.dir/big_number.cc.s
.PHONY : big_number.cc.s

binary_search.o: binary_search.cc.o

.PHONY : binary_search.o

# target to build an object file
binary_search.cc.o:
	$(MAKE) -f CMakeFiles/binary_search.dir/build.make CMakeFiles/binary_search.dir/binary_search.cc.o
.PHONY : binary_search.cc.o

binary_search.i: binary_search.cc.i

.PHONY : binary_search.i

# target to preprocess a source file
binary_search.cc.i:
	$(MAKE) -f CMakeFiles/binary_search.dir/build.make CMakeFiles/binary_search.dir/binary_search.cc.i
.PHONY : binary_search.cc.i

binary_search.s: binary_search.cc.s

.PHONY : binary_search.s

# target to generate assembly for a file
binary_search.cc.s:
	$(MAKE) -f CMakeFiles/binary_search.dir/build.make CMakeFiles/binary_search.dir/binary_search.cc.s
.PHONY : binary_search.cc.s

lc_longest_palindrome.o: lc_longest_palindrome.cc.o

.PHONY : lc_longest_palindrome.o

# target to build an object file
lc_longest_palindrome.cc.o:
	$(MAKE) -f CMakeFiles/lc_longest_palindrome.dir/build.make CMakeFiles/lc_longest_palindrome.dir/lc_longest_palindrome.cc.o
.PHONY : lc_longest_palindrome.cc.o

lc_longest_palindrome.i: lc_longest_palindrome.cc.i

.PHONY : lc_longest_palindrome.i

# target to preprocess a source file
lc_longest_palindrome.cc.i:
	$(MAKE) -f CMakeFiles/lc_longest_palindrome.dir/build.make CMakeFiles/lc_longest_palindrome.dir/lc_longest_palindrome.cc.i
.PHONY : lc_longest_palindrome.cc.i

lc_longest_palindrome.s: lc_longest_palindrome.cc.s

.PHONY : lc_longest_palindrome.s

# target to generate assembly for a file
lc_longest_palindrome.cc.s:
	$(MAKE) -f CMakeFiles/lc_longest_palindrome.dir/build.make CMakeFiles/lc_longest_palindrome.dir/lc_longest_palindrome.cc.s
.PHONY : lc_longest_palindrome.cc.s

lc_longest_substring.o: lc_longest_substring.cc.o

.PHONY : lc_longest_substring.o

# target to build an object file
lc_longest_substring.cc.o:
	$(MAKE) -f CMakeFiles/lc_longest_substring.dir/build.make CMakeFiles/lc_longest_substring.dir/lc_longest_substring.cc.o
.PHONY : lc_longest_substring.cc.o

lc_longest_substring.i: lc_longest_substring.cc.i

.PHONY : lc_longest_substring.i

# target to preprocess a source file
lc_longest_substring.cc.i:
	$(MAKE) -f CMakeFiles/lc_longest_substring.dir/build.make CMakeFiles/lc_longest_substring.dir/lc_longest_substring.cc.i
.PHONY : lc_longest_substring.cc.i

lc_longest_substring.s: lc_longest_substring.cc.s

.PHONY : lc_longest_substring.s

# target to generate assembly for a file
lc_longest_substring.cc.s:
	$(MAKE) -f CMakeFiles/lc_longest_substring.dir/build.make CMakeFiles/lc_longest_substring.dir/lc_longest_substring.cc.s
.PHONY : lc_longest_substring.cc.s

lc_median_of_two_sorted_array.o: lc_median_of_two_sorted_array.cc.o

.PHONY : lc_median_of_two_sorted_array.o

# target to build an object file
lc_median_of_two_sorted_array.cc.o:
	$(MAKE) -f CMakeFiles/lc_median_of_two_sorted_array.dir/build.make CMakeFiles/lc_median_of_two_sorted_array.dir/lc_median_of_two_sorted_array.cc.o
.PHONY : lc_median_of_two_sorted_array.cc.o

lc_median_of_two_sorted_array.i: lc_median_of_two_sorted_array.cc.i

.PHONY : lc_median_of_two_sorted_array.i

# target to preprocess a source file
lc_median_of_two_sorted_array.cc.i:
	$(MAKE) -f CMakeFiles/lc_median_of_two_sorted_array.dir/build.make CMakeFiles/lc_median_of_two_sorted_array.dir/lc_median_of_two_sorted_array.cc.i
.PHONY : lc_median_of_two_sorted_array.cc.i

lc_median_of_two_sorted_array.s: lc_median_of_two_sorted_array.cc.s

.PHONY : lc_median_of_two_sorted_array.s

# target to generate assembly for a file
lc_median_of_two_sorted_array.cc.s:
	$(MAKE) -f CMakeFiles/lc_median_of_two_sorted_array.dir/build.make CMakeFiles/lc_median_of_two_sorted_array.dir/lc_median_of_two_sorted_array.cc.s
.PHONY : lc_median_of_two_sorted_array.cc.s

lc_reverse_int.o: lc_reverse_int.cc.o

.PHONY : lc_reverse_int.o

# target to build an object file
lc_reverse_int.cc.o:
	$(MAKE) -f CMakeFiles/lc_reverse_int.dir/build.make CMakeFiles/lc_reverse_int.dir/lc_reverse_int.cc.o
.PHONY : lc_reverse_int.cc.o

lc_reverse_int.i: lc_reverse_int.cc.i

.PHONY : lc_reverse_int.i

# target to preprocess a source file
lc_reverse_int.cc.i:
	$(MAKE) -f CMakeFiles/lc_reverse_int.dir/build.make CMakeFiles/lc_reverse_int.dir/lc_reverse_int.cc.i
.PHONY : lc_reverse_int.cc.i

lc_reverse_int.s: lc_reverse_int.cc.s

.PHONY : lc_reverse_int.s

# target to generate assembly for a file
lc_reverse_int.cc.s:
	$(MAKE) -f CMakeFiles/lc_reverse_int.dir/build.make CMakeFiles/lc_reverse_int.dir/lc_reverse_int.cc.s
.PHONY : lc_reverse_int.cc.s

lc_two_sum.o: lc_two_sum.cc.o

.PHONY : lc_two_sum.o

# target to build an object file
lc_two_sum.cc.o:
	$(MAKE) -f CMakeFiles/lc_two_sum.dir/build.make CMakeFiles/lc_two_sum.dir/lc_two_sum.cc.o
.PHONY : lc_two_sum.cc.o

lc_two_sum.i: lc_two_sum.cc.i

.PHONY : lc_two_sum.i

# target to preprocess a source file
lc_two_sum.cc.i:
	$(MAKE) -f CMakeFiles/lc_two_sum.dir/build.make CMakeFiles/lc_two_sum.dir/lc_two_sum.cc.i
.PHONY : lc_two_sum.cc.i

lc_two_sum.s: lc_two_sum.cc.s

.PHONY : lc_two_sum.s

# target to generate assembly for a file
lc_two_sum.cc.s:
	$(MAKE) -f CMakeFiles/lc_two_sum.dir/build.make CMakeFiles/lc_two_sum.dir/lc_two_sum.cc.s
.PHONY : lc_two_sum.cc.s

sort.o: sort.cc.o

.PHONY : sort.o

# target to build an object file
sort.cc.o:
	$(MAKE) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/sort.cc.o
.PHONY : sort.cc.o

sort.i: sort.cc.i

.PHONY : sort.i

# target to preprocess a source file
sort.cc.i:
	$(MAKE) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/sort.cc.i
.PHONY : sort.cc.i

sort.s: sort.cc.s

.PHONY : sort.s

# target to generate assembly for a file
sort.cc.s:
	$(MAKE) -f CMakeFiles/sort.dir/build.make CMakeFiles/sort.dir/sort.cc.s
.PHONY : sort.cc.s

subarray.o: subarray.cc.o

.PHONY : subarray.o

# target to build an object file
subarray.cc.o:
	$(MAKE) -f CMakeFiles/subarray.dir/build.make CMakeFiles/subarray.dir/subarray.cc.o
.PHONY : subarray.cc.o

subarray.i: subarray.cc.i

.PHONY : subarray.i

# target to preprocess a source file
subarray.cc.i:
	$(MAKE) -f CMakeFiles/subarray.dir/build.make CMakeFiles/subarray.dir/subarray.cc.i
.PHONY : subarray.cc.i

subarray.s: subarray.cc.s

.PHONY : subarray.s

# target to generate assembly for a file
subarray.cc.s:
	$(MAKE) -f CMakeFiles/subarray.dir/build.make CMakeFiles/subarray.dir/subarray.cc.s
.PHONY : subarray.cc.s

tree.o: tree.cc.o

.PHONY : tree.o

# target to build an object file
tree.cc.o:
	$(MAKE) -f CMakeFiles/tree.dir/build.make CMakeFiles/tree.dir/tree.cc.o
.PHONY : tree.cc.o

tree.i: tree.cc.i

.PHONY : tree.i

# target to preprocess a source file
tree.cc.i:
	$(MAKE) -f CMakeFiles/tree.dir/build.make CMakeFiles/tree.dir/tree.cc.i
.PHONY : tree.cc.i

tree.s: tree.cc.s

.PHONY : tree.s

# target to generate assembly for a file
tree.cc.s:
	$(MAKE) -f CMakeFiles/tree.dir/build.make CMakeFiles/tree.dir/tree.cc.s
.PHONY : tree.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tree"
	@echo "... sort"
	@echo "... big_number"
	@echo "... binary_search"
	@echo "... lc_reverse_int"
	@echo "... subarray"
	@echo "... lc_longest_palindrome"
	@echo "... lc_longest_substring"
	@echo "... lc_median_of_two_sorted_array"
	@echo "... lc_two_sum"
	@echo "... big_number.o"
	@echo "... big_number.i"
	@echo "... big_number.s"
	@echo "... binary_search.o"
	@echo "... binary_search.i"
	@echo "... binary_search.s"
	@echo "... lc_longest_palindrome.o"
	@echo "... lc_longest_palindrome.i"
	@echo "... lc_longest_palindrome.s"
	@echo "... lc_longest_substring.o"
	@echo "... lc_longest_substring.i"
	@echo "... lc_longest_substring.s"
	@echo "... lc_median_of_two_sorted_array.o"
	@echo "... lc_median_of_two_sorted_array.i"
	@echo "... lc_median_of_two_sorted_array.s"
	@echo "... lc_reverse_int.o"
	@echo "... lc_reverse_int.i"
	@echo "... lc_reverse_int.s"
	@echo "... lc_two_sum.o"
	@echo "... lc_two_sum.i"
	@echo "... lc_two_sum.s"
	@echo "... sort.o"
	@echo "... sort.i"
	@echo "... sort.s"
	@echo "... subarray.o"
	@echo "... subarray.i"
	@echo "... subarray.s"
	@echo "... tree.o"
	@echo "... tree.i"
	@echo "... tree.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

